### ISSUE TITLE
Your Matrix server (synapse) is outdated, we cannot communicate with you!

### ISSUE THREAD

**Issue by maxidorius** [FabricLabs/chat.fabric.pub#12]
All in the title, you're still on 0.99.2 and federation is no longer working with you. I have been trying to talk to you for ages - please update!

See federation tester: https://federationtester.matrix.org/api/report?server_name=fabric.pub

`"federationOk": false`

**Comment by martindale** [comment]
Running into this:

```
$ pip install --upgrade matrix-synapse[all]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting matrix-synapse[all]
  Using cached https://files.pythonhosted.org/packages/52/20/f12285bf6c2198a1f8d858687840860d2eb308f558ef2f0e8ba1cd893e4f/matrix-synapse-1.0.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/synapse/bin/python2.7 /opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpHpqhe8
       cwd: /tmp/pip-install-OWkZAp/matrix-synapse
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: 'module' object has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/synapse/bin/python2.7 /opt/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpHpqhe8 Check the logs for full command output.
```

**Comment by maxidorius** [comment]
python2 is no longer supported in recent versions of synapse, you need python3, and ideally you should do it via a virtualenv (recommendation of Matrix.org)

**Comment by martindale** [comment]
We are using virtualenv, but it seems to be hard-locking me into Python 2.x.  Is there no way to switch an existing environment over to Python 3?

**Comment by maxidorius** [comment]
I don't know I'm afraid :( I always installed synapse using deb packages
